---

- name: Installing Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Process Nginx
  service:
    name: nginx
    state: started

- name: Add prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Add prometheus directory
  file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'

- name: Add prometheus directory
  file:
    path: /var/log/prometheus
    state: directory
    mode: '0755'

- name: Add /var/run/prometheus directory
  file:
    path: /var/run/prometheus
    state: directory
    mode: '0755'

- name: Install Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: prometheus_archive

- name: Copy prometheus conf directory to /usr/local/bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus /usr/local/bin/"
  when: prometheus_archive.changed

- name: Copy promtool file to /usr/local/bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/promtool /usr/local/bin/"
  when: prometheus_archive.changed

- name: Enable prometheus to execute
  file:
    path: /usr/local/bin/prometheus
    mode: u+x,g+x,o+x

- name: Enable promtool to execute
  file:
    path: /usr/local/bin/promtool
    mode: u+x,g+x,o+x

- name: Copy prometheus.yml file to /etc/prometheus
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus.yml /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copy consoles to /etc/promethus
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/consoles /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copy console_libraries to /etc/promethus
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/console_libraries /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copy Prometheus systemd.service to /etc/systemd/system/prometheus.service
  copy:
    src: "{{ src }}"
    dest: /etc/systemd/system/prometheus.service
    mode: '0755'

- name: Start and enable Prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
